# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: controlplane.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'controlplane.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ontrolplane.proto\x12\x0c\x63ontrolplane\"W\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0bpickup_node\x18\x02 \x01(\x05\x12\x14\n\x0c\x64ropoff_node\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"g\n\x0b\x44ispatchAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x14\n\x0cowner_region\x18\x02 \x01(\x05\x12\x15\n\x08\x61ssignee\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x0c\n\x04note\x18\x04 \x01(\tB\x0b\n\t_assignee\"@\n\nLeaderInfo\x12\x11\n\tregion_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x62ot_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\">\n\x16\x44iscoverLeadersRequest\x12\x16\n\tregion_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x0c\n\n_region_id\"\x95\x01\n\x17\x44iscoverLeadersResponse\x12)\n\x07leaders\x18\x01 \x03(\x0b\x32\x18.controlplane.LeaderInfo\x12\x16\n\x0eself_region_id\x18\x02 \x01(\x05\x12\x1a\n\x12self_leader_bot_id\x18\x03 \x01(\x05\x12\x1b\n\x13self_leader_address\x18\x04 \x01(\t2\xb6\x01\n\x13\x43ontrolPlaneService\x12?\n\rDispatchOrder\x12\x13.controlplane.Order\x1a\x19.controlplane.DispatchAck\x12^\n\x0f\x44iscoverLeaders\x12$.controlplane.DiscoverLeadersRequest\x1a%.controlplane.DiscoverLeadersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controlplane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=36
  _globals['_ORDER']._serialized_end=123
  _globals['_DISPATCHACK']._serialized_start=125
  _globals['_DISPATCHACK']._serialized_end=228
  _globals['_LEADERINFO']._serialized_start=230
  _globals['_LEADERINFO']._serialized_end=294
  _globals['_DISCOVERLEADERSREQUEST']._serialized_start=296
  _globals['_DISCOVERLEADERSREQUEST']._serialized_end=358
  _globals['_DISCOVERLEADERSRESPONSE']._serialized_start=361
  _globals['_DISCOVERLEADERSRESPONSE']._serialized_end=510
  _globals['_CONTROLPLANESERVICE']._serialized_start=513
  _globals['_CONTROLPLANESERVICE']._serialized_end=695
# @@protoc_insertion_point(module_scope)
