# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/controlplane.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/controlplane.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/controlplane.proto\x12\x0c\x63ontrolplane\"W\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0bpickup_node\x18\x02 \x01(\x05\x12\x14\n\x0c\x64ropoff_node\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"g\n\x0b\x44ispatchAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x14\n\x0cowner_region\x18\x02 \x01(\x05\x12\x15\n\x08\x61ssignee\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x0c\n\x04note\x18\x04 \x01(\tB\x0b\n\t_assignee2V\n\x13\x43ontrolPlaneService\x12?\n\rDispatchOrder\x12\x13.controlplane.Order\x1a\x19.controlplane.DispatchAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.controlplane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=42
  _globals['_ORDER']._serialized_end=129
  _globals['_DISPATCHACK']._serialized_start=131
  _globals['_DISPATCHACK']._serialized_end=234
  _globals['_CONTROLPLANESERVICE']._serialized_start=236
  _globals['_CONTROLPLANESERVICE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
