# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import controlplane_pb2 as proto_dot_controlplane__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/controlplane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPlaneServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DispatchOrder = channel.unary_unary(
                '/controlplane.ControlPlaneService/DispatchOrder',
                request_serializer=proto_dot_controlplane__pb2.Order.SerializeToString,
                response_deserializer=proto_dot_controlplane__pb2.DispatchAck.FromString,
                _registered_method=True)


class ControlPlaneServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def DispatchOrder(self, request, context):
        """Submit an order to ANY bot.

        Routing is entirely the fleet's job: the control plane knows no regions
        and no leaders. A non-leader forwards to its leader; a leader resolves
        pickup_node's region from its own map and forwards to that region's
        leader. Idempotent on order_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DispatchOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchOrder,
                    request_deserializer=proto_dot_controlplane__pb2.Order.FromString,
                    response_serializer=proto_dot_controlplane__pb2.DispatchAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controlplane.ControlPlaneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('controlplane.ControlPlaneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlaneService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DispatchOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controlplane.ControlPlaneService/DispatchOrder',
            proto_dot_controlplane__pb2.Order.SerializeToString,
            proto_dot_controlplane__pb2.DispatchAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
