# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import fleet_pb2 as proto_dot_fleet__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/fleet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegionServiceStub:
    """--- RegionService: bot <-> own leader ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/fleet.RegionService/Heartbeat',
                request_serializer=proto_dot_fleet__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.HeartbeatAck.FromString,
                _registered_method=True)
        self.Departure = channel.unary_unary(
                '/fleet.RegionService/Departure',
                request_serializer=proto_dot_fleet__pb2.DepartureRequest.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.DepartureAck.FromString,
                _registered_method=True)
        self.MigrationRequest = channel.unary_unary(
                '/fleet.RegionService/MigrationRequest',
                request_serializer=proto_dot_fleet__pb2.MigrationReq.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.MigrationReqAck.FromString,
                _registered_method=True)


class RegionServiceServicer:
    """--- RegionService: bot <-> own leader ---

    """

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Departure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MigrationRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_fleet__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_fleet__pb2.HeartbeatAck.SerializeToString,
            ),
            'Departure': grpc.unary_unary_rpc_method_handler(
                    servicer.Departure,
                    request_deserializer=proto_dot_fleet__pb2.DepartureRequest.FromString,
                    response_serializer=proto_dot_fleet__pb2.DepartureAck.SerializeToString,
            ),
            'MigrationRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.MigrationRequest,
                    request_deserializer=proto_dot_fleet__pb2.MigrationReq.FromString,
                    response_serializer=proto_dot_fleet__pb2.MigrationReqAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.RegionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.RegionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegionService:
    """--- RegionService: bot <-> own leader ---

    """

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.RegionService/Heartbeat',
            proto_dot_fleet__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_fleet__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Departure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.RegionService/Departure',
            proto_dot_fleet__pb2.DepartureRequest.SerializeToString,
            proto_dot_fleet__pb2.DepartureAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MigrationRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.RegionService/MigrationRequest',
            proto_dot_fleet__pb2.MigrationReq.SerializeToString,
            proto_dot_fleet__pb2.MigrationReqAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class JobServiceStub:
    """Accepts new jobs. Served by every bot; a non-leader or a leader of the
    wrong region forwards to the pickup node's region leader.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/fleet.JobService/SubmitJob',
                request_serializer=proto_dot_fleet__pb2.Job.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.JobAck.FromString,
                _registered_method=True)


class JobServiceServicer:
    """Accepts new jobs. Served by every bot; a non-leader or a leader of the
    wrong region forwards to the pickup node's region leader.
    """

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=proto_dot_fleet__pb2.Job.FromString,
                    response_serializer=proto_dot_fleet__pb2.JobAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService:
    """Accepts new jobs. Served by every bot; a non-leader or a leader of the
    wrong region forwards to the pickup node's region leader.
    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.JobService/SubmitJob',
            proto_dot_fleet__pb2.Job.SerializeToString,
            proto_dot_fleet__pb2.JobAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BotServiceStub:
    """Served by every bot: a leader hands a job to one of its followers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssignJob = channel.unary_unary(
                '/fleet.BotService/AssignJob',
                request_serializer=proto_dot_fleet__pb2.Job.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.JobAck.FromString,
                _registered_method=True)


class BotServiceServicer:
    """Served by every bot: a leader hands a job to one of its followers.
    """

    def AssignJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssignJob': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignJob,
                    request_deserializer=proto_dot_fleet__pb2.Job.FromString,
                    response_serializer=proto_dot_fleet__pb2.JobAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.BotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.BotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BotService:
    """Served by every bot: a leader hands a job to one of its followers.
    """

    @staticmethod
    def AssignJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.BotService/AssignJob',
            proto_dot_fleet__pb2.Job.SerializeToString,
            proto_dot_fleet__pb2.JobAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReservationServiceStub:
    """Served by every bot; callers must be in the same region, the same rule the
    virtual network applies to RegionService and ElectionService (§12).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Announce = channel.unary_unary(
                '/fleet.ReservationService/Announce',
                request_serializer=proto_dot_fleet__pb2.ReservationAnnounce.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.ReservationAck.FromString,
                _registered_method=True)


class ReservationServiceServicer:
    """Served by every bot; callers must be in the same region, the same rule the
    virtual network applies to RegionService and ElectionService (§12).
    """

    def Announce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Announce': grpc.unary_unary_rpc_method_handler(
                    servicer.Announce,
                    request_deserializer=proto_dot_fleet__pb2.ReservationAnnounce.FromString,
                    response_serializer=proto_dot_fleet__pb2.ReservationAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.ReservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.ReservationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReservationService:
    """Served by every bot; callers must be in the same region, the same rule the
    virtual network applies to RegionService and ElectionService (§12).
    """

    @staticmethod
    def Announce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.ReservationService/Announce',
            proto_dot_fleet__pb2.ReservationAnnounce.SerializeToString,
            proto_dot_fleet__pb2.ReservationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AdminServiceStub:
    """--- Admin: introspection ---
    For operators and the Docker test harness. Only served when ADMIN_ENABLED=1
    (the virtual network refuses it otherwise).

    Read-only. It used to carry InjectRobotState and InjectObstruction, which put
    a robot snapshot or a blockage straight into the bot around the QR read, the
    companion and the wire. A robot reports over spore.network.v1.RobotNetwork
    now, like a robot; see proto/robot.proto.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/fleet.AdminService/GetState',
                request_serializer=proto_dot_fleet__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.BotState.FromString,
                _registered_method=True)


class AdminServiceServicer:
    """--- Admin: introspection ---
    For operators and the Docker test harness. Only served when ADMIN_ENABLED=1
    (the virtual network refuses it otherwise).

    Read-only. It used to carry InjectRobotState and InjectObstruction, which put
    a robot snapshot or a blockage straight into the bot around the QR read, the
    companion and the wire. A robot reports over spore.network.v1.RobotNetwork
    now, like a robot; see proto/robot.proto.

    """

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=proto_dot_fleet__pb2.Empty.FromString,
                    response_serializer=proto_dot_fleet__pb2.BotState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService:
    """--- Admin: introspection ---
    For operators and the Docker test harness. Only served when ADMIN_ENABLED=1
    (the virtual network refuses it otherwise).

    Read-only. It used to carry InjectRobotState and InjectObstruction, which put
    a robot snapshot or a blockage straight into the bot around the QR read, the
    companion and the wire. A robot reports over spore.network.v1.RobotNetwork
    now, like a robot; see proto/robot.proto.

    """

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.AdminService/GetState',
            proto_dot_fleet__pb2.Empty.SerializeToString,
            proto_dot_fleet__pb2.BotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LeaderExchangeServiceStub:
    """--- LeaderExchangeService: leader <-> leader ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LeaderHeartbeat = channel.unary_unary(
                '/fleet.LeaderExchangeService/LeaderHeartbeat',
                request_serializer=proto_dot_fleet__pb2.LeaderHBRequest.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.LeaderHBAck.FromString,
                _registered_method=True)
        self.MigrationHandoff = channel.unary_unary(
                '/fleet.LeaderExchangeService/MigrationHandoff',
                request_serializer=proto_dot_fleet__pb2.MigrationHandoffReq.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.MigrationHandoffAck.FromString,
                _registered_method=True)
        self.ForwardJob = channel.unary_unary(
                '/fleet.LeaderExchangeService/ForwardJob',
                request_serializer=proto_dot_fleet__pb2.ForwardJobReq.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.JobAck.FromString,
                _registered_method=True)
        self.JobEvent = channel.unary_unary(
                '/fleet.LeaderExchangeService/JobEvent',
                request_serializer=proto_dot_fleet__pb2.Job.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.JobEventAck.FromString,
                _registered_method=True)


class LeaderExchangeServiceServicer:
    """--- LeaderExchangeService: leader <-> leader ---

    """

    def LeaderHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MigrationHandoff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardJob(self, request, context):
        """"Nobody here is free — can your region take this job?"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JobEvent(self, request, context):
        """A leader observed something about a job it does not own (the assignee
        migrated into its region and then delivered / failed / vanished).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeaderExchangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LeaderHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaderHeartbeat,
                    request_deserializer=proto_dot_fleet__pb2.LeaderHBRequest.FromString,
                    response_serializer=proto_dot_fleet__pb2.LeaderHBAck.SerializeToString,
            ),
            'MigrationHandoff': grpc.unary_unary_rpc_method_handler(
                    servicer.MigrationHandoff,
                    request_deserializer=proto_dot_fleet__pb2.MigrationHandoffReq.FromString,
                    response_serializer=proto_dot_fleet__pb2.MigrationHandoffAck.SerializeToString,
            ),
            'ForwardJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardJob,
                    request_deserializer=proto_dot_fleet__pb2.ForwardJobReq.FromString,
                    response_serializer=proto_dot_fleet__pb2.JobAck.SerializeToString,
            ),
            'JobEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.JobEvent,
                    request_deserializer=proto_dot_fleet__pb2.Job.FromString,
                    response_serializer=proto_dot_fleet__pb2.JobEventAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.LeaderExchangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.LeaderExchangeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LeaderExchangeService:
    """--- LeaderExchangeService: leader <-> leader ---

    """

    @staticmethod
    def LeaderHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.LeaderExchangeService/LeaderHeartbeat',
            proto_dot_fleet__pb2.LeaderHBRequest.SerializeToString,
            proto_dot_fleet__pb2.LeaderHBAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MigrationHandoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.LeaderExchangeService/MigrationHandoff',
            proto_dot_fleet__pb2.MigrationHandoffReq.SerializeToString,
            proto_dot_fleet__pb2.MigrationHandoffAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.LeaderExchangeService/ForwardJob',
            proto_dot_fleet__pb2.ForwardJobReq.SerializeToString,
            proto_dot_fleet__pb2.JobAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JobEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.LeaderExchangeService/JobEvent',
            proto_dot_fleet__pb2.Job.SerializeToString,
            proto_dot_fleet__pb2.JobEventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ElectionServiceStub:
    """--- ElectionService: bot <-> peer bot ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Elect = channel.unary_unary(
                '/fleet.ElectionService/Elect',
                request_serializer=proto_dot_fleet__pb2.ElectRequest.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.ElectResponse.FromString,
                _registered_method=True)
        self.Coordinator = channel.unary_unary(
                '/fleet.ElectionService/Coordinator',
                request_serializer=proto_dot_fleet__pb2.CoordinatorRequest.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.CoordinatorResponse.FromString,
                _registered_method=True)


class ElectionServiceServicer:
    """--- ElectionService: bot <-> peer bot ---

    """

    def Elect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Coordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ElectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Elect': grpc.unary_unary_rpc_method_handler(
                    servicer.Elect,
                    request_deserializer=proto_dot_fleet__pb2.ElectRequest.FromString,
                    response_serializer=proto_dot_fleet__pb2.ElectResponse.SerializeToString,
            ),
            'Coordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.Coordinator,
                    request_deserializer=proto_dot_fleet__pb2.CoordinatorRequest.FromString,
                    response_serializer=proto_dot_fleet__pb2.CoordinatorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.ElectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.ElectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ElectionService:
    """--- ElectionService: bot <-> peer bot ---

    """

    @staticmethod
    def Elect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.ElectionService/Elect',
            proto_dot_fleet__pb2.ElectRequest.SerializeToString,
            proto_dot_fleet__pb2.ElectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Coordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.ElectionService/Coordinator',
            proto_dot_fleet__pb2.CoordinatorRequest.SerializeToString,
            proto_dot_fleet__pb2.CoordinatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MigrationJoinServiceStub:
    """--- MigrationJoinService: bot -> destination leader ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MigrationJoin = channel.unary_unary(
                '/fleet.MigrationJoinService/MigrationJoin',
                request_serializer=proto_dot_fleet__pb2.MigrationJoinReq.SerializeToString,
                response_deserializer=proto_dot_fleet__pb2.MigrationJoinAck.FromString,
                _registered_method=True)


class MigrationJoinServiceServicer:
    """--- MigrationJoinService: bot -> destination leader ---

    """

    def MigrationJoin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MigrationJoinServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MigrationJoin': grpc.unary_unary_rpc_method_handler(
                    servicer.MigrationJoin,
                    request_deserializer=proto_dot_fleet__pb2.MigrationJoinReq.FromString,
                    response_serializer=proto_dot_fleet__pb2.MigrationJoinAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.MigrationJoinService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.MigrationJoinService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MigrationJoinService:
    """--- MigrationJoinService: bot -> destination leader ---

    """

    @staticmethod
    def MigrationJoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.MigrationJoinService/MigrationJoin',
            proto_dot_fleet__pb2.MigrationJoinReq.SerializeToString,
            proto_dot_fleet__pb2.MigrationJoinAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
