# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import robot_pb2 as proto_dot_robot__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/robot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotNetworkStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/spore.network.v1.RobotNetwork/Session',
                request_serializer=proto_dot_robot__pb2.RobotToNetwork.SerializeToString,
                response_deserializer=proto_dot_robot__pb2.NetworkToRobot.FromString,
                _registered_method=True)


class RobotNetworkServicer:
    """Missing associated documentation comment in .proto file."""

    def Session(self, request_iterator, context):
        """One long-lived bidirectional stream per robot. The robot (the companion,
        acting for its robot) is the client; the network layer is the server --
        and the server is *this robot's own bot*, not a service for the fleet.
        Why: spore-amr/network-layer/docs/boundary.md.

        The stream types name the direction, so there is no envelope and no
        `schema` discriminator to get wrong: what a robot may send and what it may
        receive are different types, and the compiler enforces it.

        A stream is ordered and reliable, so no sequence numbers: a command and a
        status can never be reordered, and `timestamp` is a data value, not a
        transport concern.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotNetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=proto_dot_robot__pb2.RobotToNetwork.FromString,
                    response_serializer=proto_dot_robot__pb2.NetworkToRobot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spore.network.v1.RobotNetwork', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spore.network.v1.RobotNetwork', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotNetwork:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/spore.network.v1.RobotNetwork/Session',
            proto_dot_robot__pb2.RobotToNetwork.SerializeToString,
            proto_dot_robot__pb2.NetworkToRobot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
