[project]
name = "spore-warehouse-layout"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = []
requires-python = ">=3.13"
dependencies = []

[project.scripts]
spore-warehouse-layout = "spore_warehouse_layout:run"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
