"""Shared fixtures.

The real 881-node map generated by `spore-warehouse-layout` is committed to the
repo, so it is the primary fixture: the planner is tested against the floor plan it
will actually run on, not a synthetic stand-in. `make_map` builds the small maps
needed to isolate a single scenario.
"""

from __future__ import annotations

from pathlib import Path

from planning.graph import Graph
from planning.geometry import NodeType
from warehouse.map import WarehouseMap

#: The real 881-node layout, used wherever a test should run against the floor
#: the fleet actually drives on rather than a synthetic stand-in.
REPO_ROOT = Path(__file__).resolve().parents[3]
REAL_MAP_PATH = REPO_ROOT / "spore-warehouse-layout" / "output" / "warehouse.json"

SPACING = 200


def make_map_doc(
    cells: dict[tuple[int, int], str],
    *,
    spacing: int = SPACING,
    density: str = "sparse",
) -> dict:
    """Build a map document from grid cells.

    `cells` maps integer grid coordinates to a node type; edges are created between
    every pair of orthogonally adjacent cells. That is enough to express every shape
    the scenario tests need -- corridors, junctions, dead-end spurs -- without
    hand-writing node ids and edge lists.
    """
    ordered = sorted(cells)
    ids = {cell: i for i, cell in enumerate(ordered)}
    nodes = [
        {
            "id": ids[(gx, gy)],
            "name": f"n{ids[(gx, gy)]}",
            "region_id": 1,
            "node_type": cells[(gx, gy)],
            "position": {"x": float(gx * spacing), "y": float(gy * spacing)},
        }
        for gx, gy in ordered
    ]
    edges = []
    for gx, gy in ordered:
        for dx, dy in ((1, 0), (0, 1)):
            neighbour = (gx + dx, gy + dy)
            if neighbour in cells:
                edges.append(
                    {"a": ids[(gx, gy)], "b": ids[neighbour], "length": spacing}
                )
    max_x = max(gx for gx, _ in ordered) * spacing
    max_y = max(gy for _, gy in ordered) * spacing
    return {
        "schema_version": "v0.1.0",
        "units": "cm",
        "node_spacing": spacing,
        "dimensions": {"width": max_x + spacing, "height": max_y + spacing},
        "regions": [
            {"id": 1, "name": "test", "density": density, "description": "test region"}
        ],
        "nodes": nodes,
        "edges": edges,
    }


def make_map(cells: dict[tuple[int, int], str], **kwargs) -> WarehouseMap:
    return WarehouseMap(make_map_doc(cells, **kwargs))


def make_graph(cells: dict[tuple[int, int], str], **kwargs) -> Graph:
    return Graph(make_map(cells, **kwargs))


def line(length: int, node_type: str = NodeType.PT.value) -> dict[tuple[int, int], str]:
    """A straight west-east corridor of `length` nodes."""
    return {(x, 0): node_type for x in range(length)}
