"""Generate the world, the compose file, and per-robot configs from fleet.yaml.

One manifest is the source of truth, so a robot's name in the world can never
drift from the `--robot-name` its container connects with.
"""

import argparse
import math
import pathlib
from typing import List, Tuple

import yaml

from tools.manifest import TrackConfig, deep_merge

# Identity orientation looks along +x with +z up. This rotation maps x -> -z and
# z -> +y, so the camera looks straight down with world +y up in the image,
# matching how the track texture is laid out.
TOP_DOWN_ORIENTATION = "orientation -0.5774 0.5774 0.5774 2.0944"
FIELD_OF_VIEW = math.pi / 4
VIEW_MARGIN = 1.15

CONTROLLER_IMAGE = "sih2026/controller:dev"
SIM_IMAGE = "sih2026/sim:dev"


def sensor_offsets(count: int, spacing: float) -> Tuple[float, ...]:
    """Lateral sensor positions, left to right, in the robot frame (+y left)."""
    first = (count - 1) / 2 * spacing
    return tuple(first - i * spacing for i in range(count))


def viewpoint_height(plane_size, field_of_view: float = FIELD_OF_VIEW) -> float:
    """Camera height that fits the whole ground plane in view."""
    half = max(plane_size) / 2
    return half / math.tan(field_of_view / 2) * VIEW_MARGIN


def robot_configs(manifest: dict) -> List[dict]:
    defaults = manifest.get("defaults") or {}
    robot_block = manifest.get("robot") or {}
    offsets = sensor_offsets(
        count=robot_block.get("sensor_count", 3),
        spacing=robot_block.get("sensor_spacing", 0.02),
    )

    configs = []
    seen = set()
    for entry in manifest["robots"]:
        name = entry["name"]
        if name in seen:
            raise ValueError("duplicate robot name {!r} in the manifest".format(name))
        seen.add(name)

        overrides = {k: v for k, v in entry.items() if k not in ("name", "pose")}
        merged = deep_merge(defaults, overrides)
        merged["name"] = name
        merged["pose"] = entry.get("pose") or {"x": 0.0, "y": 0.0, "theta": 0.0}
        merged.setdefault("sensors", {})
        merged["sensors"] = deep_merge({"offsets": offsets}, merged["sensors"])
        configs.append(merged)

    return configs


def world_source(manifest: dict) -> str:
    track = TrackConfig.from_dict(manifest["track"])
    robot_block = manifest.get("robot") or {}
    plane_x, plane_y = track.plane_size

    header = '''#VRML_SIM R2025a utf8

EXTERNPROTO "../protos/LineBot.proto"

WorldInfo {{
  info [
    "Generated by tools/gen_fleet.py -- edit fleet.yaml, not this file."
  ]
  basicTimeStep 16
  contactProperties [
    ContactProperties {{
      material1 "slippery"
      coulombFriction [
        0
      ]
    }}
  ]
}}
Viewpoint {{
  {orientation}
  position 0 0 {height}
}}
Background {{
  skyColor [
    0.6 0.7 0.85
  ]
}}
DirectionalLight {{
  direction 0.3 0.4 -1
  intensity 2.5
  castShadows FALSE
}}
DEF GROUND Solid {{
  children [
    Shape {{
      appearance PBRAppearance {{
        baseColor 1 1 1
        roughness 0
        metalness 0
        baseColorMap ImageTexture {{
          url [
            "../textures/track.png"
          ]
        }}
      }}
      geometry Plane {{
        size {plane_x} {plane_y}
      }}
    }}
  ]
  name "ground"
  boundingObject Plane {{
  }}
}}
'''.format(plane_x=plane_x, plane_y=plane_y,
           orientation=TOP_DOWN_ORIENTATION,
           height=round(viewpoint_height(track.plane_size), 3))

    body = []
    for config in robot_configs(manifest):
        pose = config["pose"]
        body.append('''LineBot {{
  translation {x} {y} 0.02
  rotation 0 0 1 {theta}
  name "{name}"
  controller "<extern>"
  sensorCount {count}
  sensorSpacing {spacing}
  sensorHeight {height}
}}
'''.format(
            x=pose.get("x", 0.0),
            y=pose.get("y", 0.0),
            theta=pose.get("theta", 0.0),
            name=config["name"],
            count=robot_block.get("sensor_count", 3),
            spacing=robot_block.get("sensor_spacing", 0.02),
            height=robot_block.get("sensor_height", 0.015),
        ))

    return header + "".join(body)


def compose_source(manifest: dict) -> dict:
    services = {}
    for config in robot_configs(manifest):
        name = config["name"]
        resources = config.get("resources") or {}
        services[name] = {
            "image": CONTROLLER_IMAGE,
            "depends_on": ["sim"],
            "volumes": ["./:/project"],
            "working_dir": "/project",
            "user": "${DOCKER_USER:-1000:1000}",
            "init": True,
            "environment": {
                "ROBOT_NAME": name,
                "CONFIG": "/project/config/{}.yaml".format(name),
                "TELEMETRY": "/project/out/{}.csv".format(name),
                "SIM_HOST": "sim",
                "MISSION_DURATION": "${{MISSION_DURATION:-{}}}".format(
                    config.get("mission_duration_s", 120)),
            },
            "mem_limit": resources.get("memory", "256m"),
            "cpus": resources.get("cpus", "0.5"),
        }

    return {"services": services}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=pathlib.Path, default=pathlib.Path("fleet.yaml"))
    args = parser.parse_args(argv)

    manifest = yaml.safe_load(args.manifest.read_text())

    pathlib.Path("worlds").mkdir(exist_ok=True)
    pathlib.Path("worlds/track.wbt").write_text(world_source(manifest))

    compose = compose_source(manifest)
    pathlib.Path("compose.fleet.yml").write_text(
        "# Generated by tools/gen_fleet.py -- edit fleet.yaml, not this file.\n"
        + yaml.safe_dump(compose, sort_keys=True)
    )

    config_dir = pathlib.Path("config")
    config_dir.mkdir(exist_ok=True)
    for config in robot_configs(manifest):
        document = {
            "name": config["name"],
            "sensors": {k: (list(v) if isinstance(v, tuple) else v)
                        for k, v in config["sensors"].items()},
            "control": config.get("control") or {},
        }
        (config_dir / "{}.yaml".format(config["name"])).write_text(
            "# Generated by tools/gen_fleet.py -- edit fleet.yaml, not this file.\n"
            + yaml.safe_dump(document, sort_keys=True)
        )

    print("generated worlds/track.wbt, compose.fleet.yml, and {} config file(s)".format(
        len(manifest["robots"])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
